project_id = "jiqaagffzlpeionbnntg"

[functions.generate-scenes]
verify_jwt = false

[functions.generate-image]
verify_jwt = false

[functions.generate-voiceover]
verify_jwt = false

[functions.export-video]
verify_jwt = false

[functions.submit-scene-job]
verify_jwt = false

[functions.check-job-status]
verify_jwt = false

[functions.process-scene-job]
verify_jwt = true
